### PR TITLE
Images to the center

### PR DESCRIPTION
**Pull request by AnshumanDhiman**
Signed-off-by: AnshumanDhiman <67755381+AnshumanDhiman@users.noreply.github.com>

### CODE REVIEW

**Comment by AnshumanDhiman** [comment]
@ishika1727 can this be accepted

**Comment by ishika1727** [comment]
@AnshumanDhiman can you attach a screenshot of the changes made

**Comment by AnshumanDhiman** [comment]
image_2021-10-01_231320

The pre added images are now at the center of the webpage which gives them a more catchy look

**Review by ishika1727 — APPROVED** [review]

**Comment by ishika1727** [comment]
Looks good to me. Merging the PR now.

**Pull request merged**
